# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 926d58d0e5b164eb9474686e765fc3f29fdb58c6b6a9e0d37a195c80a9e0540cc59edf5b29d1bee7c86f84f3ddcb0537a0d11a3eaa0c2bfb561a030d00a8c413

test:
  secret_key_base: e172e9b2060d5671566a0486e171d8de0d5db3ac794e32a6f4d313ac7ec7fb212aacbe5285550dcb56a7028c7d785328123e19594f0df07bfbadd6d3893801c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
